package mx.ciencias.is.capisoft.modelo;
// Generated Apr 5, 2018 2:00:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private int idComentario;
     private Comentario respuesta;
     private Pregunta pregunta;
     private Usuario usuario;
     private String comentario;
     private Date fecha;
     private Set comentarios = new HashSet(0);

    public Comentario() {
    }

	
    public Comentario(int idComentario) {
        this.idComentario = idComentario;
    }
    public Comentario(int idComentario, Comentario comentario, Pregunta pregunta, Usuario usuario, String comentario_1, Date fecha, Set comentarios) {
       this.idComentario = idComentario;
       this.respuesta = comentario;
       this.pregunta = pregunta;
       this.usuario = usuario;
       this.comentario = comentario_1;
       this.fecha = fecha;
       this.comentarios = comentarios;
    }
   
    public int getIdComentario() {
        return this.idComentario;
    }
    
    public void setIdComentario(int idComentario) {
        this.idComentario = idComentario;
    }
    public Comentario getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(Comentario respuesta) {
        this.respuesta = respuesta;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


