package mx.ciencias.is.capisoft.modelo;
// Generated Apr 5, 2018 2:00:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int idPregunta;
     private Usuario usuario;
     private String titulo;
     private String pregunta;
     private Date fechaPublicacion;
     private Set comentarios = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Pregunta(int idPregunta, Usuario usuario, String titulo, String pregunta, Date fechaPublicacion, Set comentarios) {
       this.idPregunta = idPregunta;
       this.usuario = usuario;
       this.titulo = titulo;
       this.pregunta = pregunta;
       this.fechaPublicacion = fechaPublicacion;
       this.comentarios = comentarios;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


