package mx.ciencias.is.capisoft.modelo;
// Generated Mar 23, 2018 10:36:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String correo;
     private String nombreUsuario;
     private String contrasena;
     private String rutaFoto;
     private Date fechaRegistro;
     private String rol;
     private Set preguntas = new HashSet(0);
     private Set comentarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String correo) {
        this.correo = correo;
    }
    public Usuario(String correo, String nombreUsuario, String contrasena, String rutaFoto, Date fechaRegistro, String rol, Set preguntas, Set comentarios) {
       this.correo = correo;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.rutaFoto = rutaFoto;
       this.fechaRegistro = fechaRegistro;
       this.rol = rol;
       this.preguntas = preguntas;
       this.comentarios = comentarios;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getRutaFoto() {
        return this.rutaFoto;
    }
    
    public void setRutaFoto(String rutaFoto) {
        this.rutaFoto = rutaFoto;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


